services:
  client-backend:
    image: schedule-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    depends_on:
      - service-db
    restart: on-failure

  service-db:
    image: postgres
    environment:
      POSTGRES_DB: schedule_db
      POSTGRES_USER: argen
      POSTGRES_PASSWORD: coolboy
    ports:
      - "5432:5432"
volumes:
  db-data: