spring:
  datasource:
    url: jdbc:postgresql://service-db:5432/schedule_db?stringtype=unspecified
    username: argen
    password: coolboy
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/master.yaml

server:
  address: 0.0.0.0
  port: 9999
